blank_issues_enabled: false
contact_links:
  - name: CubeDev Discord
    url: https://discord.com/invite/zSkcTz3
    about: If you are having trouble with the config, come and ask us in the deluxecombat-support channel
